src/index.tsx
src/modules/acquisitions/routes.ts
src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/asegurabilidad/redux/service.ts
src/modules/asegurabilidad/views/Policies/CreatePolicy.tsx
src/modules/asegurabilidad/views/Policies/Policies.tsx
src/modules/inspection/components/index.ts
src/modules/inspection/components/inspectionForm.tsx
src/modules/inspection/custom_types.ts
src/modules/inspection/index.ts
src/modules/inspection/redux/actions.ts
src/modules/inspection/redux/index.ts
src/modules/inspection/redux/reducer.ts
src/modules/inspection/redux/selectors.ts
src/modules/inspection/redux/service.ts
src/modules/inspection/redux/types.ts
src/modules/inspection/routes.ts
src/modules/inspection/views/index.ts
src/utils/components/template/sider.tsx
src/utils/index.ts
src/utils/interfaces/insurability.ts

Correciones modulo asegurabilidad

---

src/utils/components/Location/LocationModal.tsx
src/utils/components/Location/index.tsx

fix: location type list

---

src/modules/acquisitions/redux/actions/realEstates.ts
src/modules/acquisitions/redux/reducer.ts
src/modules/acquisitions/redux/types.ts
src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/asegurabilidad/redux/service.ts
src/modules/asegurabilidad/views/Policies/CreatePolicy.tsx
src/modules/asegurabilidad/views/Policies/DetailPolicies.tsx
src/modules/asegurabilidad/views/Policies/EditPolicy.tsx
src/modules/asegurabilidad/views/Policies/Policies.tsx

mejoras en los diseños y verificación de conexión con el backend

cambios en los diseños de póliza

---

src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/asegurabilidad/redux/service/policy.ts
src/modules/asegurabilidad/views/Policies/poliza.utils.ts
src/modules/inspection/routes.ts
src/modules/inspection/views/ListInspection.tsx
src/modules/inspection/views/estilo.css
src/utils/components/template/sider.tsx

tabla inspeccion

---

src/modules/acquisitions/components/RealEstateList.tsx
src/modules/acquisitions/redux/actions/realEstates.ts
src/modules/acquisitions/redux/services/projects.ts
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/asegurabilidad/redux/service/policy.ts
src/modules/asegurabilidad/views/Policies/CreatePolicy.tsx
src/modules/asegurabilidad/views/Policies/DetailPolicies.tsx
src/modules/asegurabilidad/views/Policies/Policies.tsx

union back poliza

---

src/modules/users/components/GerenalForm.tsx
src/modules/users/components/RoleForm.tsx
src/modules/users/redux/actions.ts
src/modules/users/redux/service/user.ts
src/modules/users/views/CreateUser.tsx
src/modules/users/views/EditUser.tsx
src/utils/assets/styles/views/auth.scss
src/utils/components/Location/LocationModal.tsx
src/utils/components/Location/index.tsx
src/utils/interfaces/permits.ts

user integration

---

src/modules/Inventory_record/views/InventoryRecordList.tsx
src/modules/acquisitions/components/RealEstateList.tsx
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/asegurabilidad/redux/actions.ts
src/modules/asegurabilidad/redux/service/index.ts
src/modules/asegurabilidad/redux/service/policy.ts
src/modules/asegurabilidad/views/Policies/CreatePolicy.tsx
src/modules/asegurabilidad/views/Policies/DetailPolicies.tsx
src/modules/asegurabilidad/views/Policies/EditPolicy.tsx
src/modules/asegurabilidad/views/Policies/Policies.tsx
src/utils/components/DocumentsModal/Modal.tsx
src/utils/components/DocumentsModal/index.tsx
src/utils/components/DocumentsModal/services.ts

edicion polizas

---

src/modules/acquisitions/components/en_des_globe/TableAreas.tsx
src/modules/asegurabilidad/components/PolizaForm.tsx

integracion de cambios en poliza

integracion de cambios en poliza

---

src/modules/Inventory_record/views/InventoryRecordDetail.tsx
src/modules/acquisitions/components/RealEstateForm/DataRealEstateForm.tsx
src/modules/acquisitions/components/en_des_globe/TableAreas.tsx
src/modules/acquisitions/redux/actions/index.ts
src/modules/acquisitions/redux/actions/realEstates.ts
src/modules/acquisitions/redux/reducer.ts
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/acquisitions/redux/types.ts
src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/asegurabilidad/redux/service/policy.ts
src/modules/asegurabilidad/views/Policies/Policies.tsx
src/modules/disposition/components/Precontractual/comodato/FormPrecontractualComodato.tsx
src/utils/interfaces/realEstates.ts

construcción formularios disposición

construcción formularios disposición

---

src/App.tsx
src/modules/acquisitions/components/RealEstateForm/DataRealEstateForm.tsx
src/modules/disposition/components/Contractual/FormContract.tsx
src/modules/disposition/components/Contractual/GeneralDataContract.tsx
src/modules/disposition/components/DispositionFormTags.tsx
src/modules/disposition/components/FormDisposition.tsx
src/modules/disposition/components/FormTypeDisposition.tsx
src/modules/disposition/components/Precontractual/GeneralFormPrecontractual.tsx
src/modules/disposition/components/Precontractual/Lease/FormPrecontractualLease.tsx
src/modules/disposition/components/Precontractual/Lease/FormRiskAnalysis.tsx
src/modules/disposition/components/Precontractual/comodato/FormPrecontractualComodato.tsx
src/modules/disposition/components/TableDisposition.tsx
src/modules/disposition/routes.ts
src/modules/disposition/views/Contracts/CreateContract.tsx
src/modules/disposition/views/CreateDisposition.tsx
src/modules/disposition/views/EditDisposition.tsx
src/modules/disposition/views/ListDisposition.tsx
src/utils/assets/styles/main.scss

formularios disposición

---

src/modules/acquisitions/components/RealEstateForm/AcquisitionForm.tsx
src/modules/acquisitions/components/RealEstateForm/DataRealEstateForm.tsx
src/modules/acquisitions/components/RealEstateForm/index.tsx

merge cambios cristian

---

src/App.tsx
src/modules/acquisitions/components/ProjectDetail.tsx
src/modules/acquisitions/components/RealEstateList.tsx
src/modules/acquisitions/views/Projects/DetailProject.tsx
src/modules/asegurabilidad/components/InsuranceBrokerDetail.tsx
src/modules/asegurabilidad/components/InsuranceBrokerForm.tsx
src/modules/asegurabilidad/components/InsuranceCompanyDetail.tsx
src/modules/asegurabilidad/components/InsuranceCompanyForm.tsx
src/modules/asegurabilidad/views/InsuranceBroker/DetailInsuranceBroker.tsx
src/modules/asegurabilidad/views/InsuranceCompany/DetailInsuranceCompany.tsx
src/modules/auth/components/pass_change_form.tsx
src/modules/auth/views/pass_change_modal.tsx
src/modules/disposition/routes.ts
src/modules/inspection/components/BasicInformation.tsx
src/modules/inspection/components/CreateOccupation.tsx
src/modules/inspection/components/ListInspection.tsx
src/modules/inspection/components/OccupationForm.tsx
src/modules/inspection/components/PhotographicRecordForm.tsx
src/modules/inspection/components/Report.tsx
src/modules/inspection/components/inspectionFormTags.tsx
src/modules/inspection/routes.ts
src/modules/inspection/views/inspection/InspectionCreate.tsx
src/modules/users/components/GerenalForm.tsx
src/modules/users/views/Users.tsx
src/utils/components/template/index.tsx
src/utils/components/template/template_context.tsx
src/utils/ui/card.tsx
src/utils/ui/filter_form.tsx

add filter form

---

src/modules/Inventory_record/views/InventoryRecordList.tsx
src/modules/acquisitions/components/RealEstateList.tsx
src/modules/acquisitions/components/en_des_globe/RealEstateGlobe.tsx
src/modules/acquisitions/components/en_des_globe/TablaGlobe.tsx
src/modules/acquisitions/components/en_des_globe/TableAreas.tsx
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/acquisitions/routes.ts
src/modules/asegurabilidad/views/InsuranceBroker/index.tsx
src/modules/asegurabilidad/views/InsuranceCompany/index.tsx
src/modules/asegurabilidad/views/Policies/DetailPolicies.tsx
src/modules/disposition/components/Contractual/ContractViewForm.tsx
src/modules/disposition/components/Contractual/FormContract.tsx
src/modules/disposition/components/Contractual/TableContract.tsx
src/modules/disposition/components/Precontractual/FormLider.tsx
src/modules/disposition/components/Precontractual/Formobligation.tsx
src/modules/disposition/components/Precontractual/GeneralFormPrecontractual.tsx
src/modules/disposition/components/Precontractual/Lease/FormPrecontractualLease.tsx
src/modules/disposition/components/Precontractual/Lease/FormRiskAnalysis.tsx
src/modules/disposition/components/Precontractual/PublicUse/FormPrecontractualPublicUse.tsx
src/modules/disposition/components/Precontractual/comodato/FormPrecontractualComodato.tsx
src/modules/disposition/routes.ts
src/modules/disposition/views/Contracts/DetailContract.tsx
src/modules/disposition/views/Contracts/EditContract.tsx
src/modules/disposition/views/ListDisposition.tsx
src/modules/users/redux/service/user.ts

cambios Filtros

---

src/modules/asegurabilidad/views/Policies/Policies.tsx

lista polizas

---

src/modules/acquisitions/components/ProjectModal.tsx
src/modules/acquisitions/components/RealEstateForm/index.tsx
src/modules/acquisitions/components/en_des_globe/RealEstateGlobe.tsx
src/modules/acquisitions/components/en_des_globe/TableAreas.tsx
src/modules/acquisitions/routes.ts
src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/asegurabilidad/views/Policies/CreatePolicy.tsx
src/modules/disposition/components/Precontractual/PublicUse/PublicUseDoc.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoDoc.tsx
src/modules/disposition/routes.ts
src/utils/assets/styles/comodato.css

documentos inspección

---

src/modules/disposition/components/Precontractual/comodato/ComodatoDoc.tsx
src/utils/assets/styles/comodato.css

doc comodato

---

src/modules/acquisitions/redux/actions/index.ts
src/modules/acquisitions/redux/actions/realEstates.ts
src/modules/acquisitions/redux/reducer.ts
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/acquisitions/redux/types.ts
src/modules/disposition/components/Precontractual/FormLider.tsx
src/modules/disposition/components/Precontractual/FormRiskAnalysis.tsx
src/modules/disposition/components/Precontractual/FormUser.tsx
src/modules/disposition/components/Precontractual/Formobligation.tsx
src/modules/disposition/components/Precontractual/comodato/BeneficiaryForm.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoDoc.tsx
src/modules/disposition/components/Precontractual/comodato/FormPrecontractualComodato.tsx
src/modules/disposition/components/Precontractual/comodato/GeneralFormComodato.tsx
src/modules/disposition/views/Pre-contractual/CreatePrecontractual.tsx
src/utils/assets/styles/comodato.css
src/utils/components/Location/index.tsx
src/utils/ui/months.tsx

documentos disposicion

---

src/App.tsx
src/config/routes.tsx
src/modules/acquisitions/components/RealEstateForm/RealEstateViewForm.tsx
src/modules/acquisitions/components/RealEstateForm/index.tsx
src/modules/acquisitions/components/RealEstateList.tsx
src/modules/acquisitions/views/RealEstate/DetailRealEstate.tsx
src/modules/disposition/components/Contractual/FormContract.tsx
src/modules/disposition/components/Contractual/GeneralDataContract.tsx
src/modules/disposition/components/Contractual/Lease/LeaseDocContract.tsx
src/modules/disposition/components/Contractual/comodatoContract/ComodatoDocContract.tsx
src/modules/disposition/components/Detail_disposition.tsx
src/modules/disposition/components/Precontractual/Lease/Detail_Lease.tsx
src/modules/disposition/components/Precontractual/Lease/FormPrecontractualLease.tsx
src/modules/disposition/components/Precontractual/Lease/GeneralFormLease.tsx
src/modules/disposition/components/Precontractual/Lease/LeaseDoc.tsx
src/modules/disposition/components/Precontractual/PublicUse/Detail_publicUse.tsx
src/modules/disposition/components/Precontractual/ViewPerson.tsx
src/modules/disposition/components/Precontractual/ViewRiskAnalysis.tsx
src/modules/disposition/components/Precontractual/comodato/Detail_comodato.tsx
src/modules/disposition/components/TableDisposition.tsx
src/modules/disposition/routes.ts
src/modules/disposition/views/DetailDisposition.tsx
src/modules/disposition/views/Pre-contractual/DetailPrecontractual.tsx
src/modules/document_management/redux/service.ts
src/modules/document_management/routes.ts
src/utils/assets/styles/contract_lease.css
src/utils/components/DocumentsModal/services.ts
src/utils/ui/PersonaM.tsx

visualizar disponibilidad

---

src/modules/acquisitions/components/ProjectModal.tsx
src/modules/acquisitions/components/en_des_globe/RealEstateGlobe.tsx
src/modules/acquisitions/redux/actions/index.ts
src/modules/acquisitions/views/Projects/index.tsx
src/modules/disposition/components/TableDisposition.tsx
src/modules/inspection/components/ListInspection.tsx
src/modules/inspection/components/ModalInspection.tsx
src/modules/inspection/views/inspection/index.tsx
src/modules/users/views/roles/ListRoles.tsx
src/utils/components/app_router/utils.tsx
src/utils/ui/filter_form.tsx

corrección error disposición

---

src/modules/acquisitions/components/ProjectForm.tsx
src/modules/acquisitions/components/RealEstateForm/index.tsx
src/modules/acquisitions/components/RealEstateList.tsx
src/modules/acquisitions/redux/actions/index.ts
src/modules/acquisitions/redux/actions/realEstates.ts
src/modules/acquisitions/redux/reducer.ts
src/modules/acquisitions/redux/services/projects.ts
src/modules/acquisitions/redux/types.ts
src/modules/acquisitions/views/Projects/CreateProject.tsx
src/modules/acquisitions/views/Projects/EditProject.tsx
src/modules/acquisitions/views/Projects/index.tsx
src/modules/acquisitions/views/RealEstate/DetailRealEstate.tsx
src/modules/asegurabilidad/components/InsuranceBrokerForm.tsx
src/modules/asegurabilidad/components/InsuranceCompanyForm.tsx
src/modules/asegurabilidad/redux/service/broker.ts
src/modules/asegurabilidad/redux/service/company.ts
src/modules/asegurabilidad/routes.ts
src/modules/asegurabilidad/views/InsuranceBroker/CreateInsuranceBroker.tsx
src/modules/asegurabilidad/views/InsuranceBroker/EditInsuranceBroker.tsx
src/modules/asegurabilidad/views/InsuranceCompany/CreateInsuranceCompany.tsx
src/modules/asegurabilidad/views/InsuranceCompany/EditInsuranceCompany.tsx
src/modules/asegurabilidad/views/Policies/CreatePolicy.tsx
src/modules/inspection/components/ListInspection.tsx
src/modules/inspection/components/ModalInspection.tsx
src/modules/users/components/GerenalForm.tsx
src/modules/users/components/RoleForm.tsx
src/modules/users/views/UserList.tsx
src/modules/users/views/roles/ListRoles.tsx
src/utils/ui/select.tsx

dependencias

---

src/modules/disposition/components/Contractual/Lease/LeaseContractPdf.tsx
src/modules/disposition/components/Contractual/comodatoContract/ComodatoContractPdf.tsx
src/modules/disposition/components/Contractual/comodatoContract/ComodatoDocContract.tsx
src/modules/disposition/components/Precontractual/Lease/LeaseDoc.tsx
src/modules/disposition/components/Precontractual/PublicUse/PubilcUsePdf.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoDoc.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoPdf.tsx
src/modules/inspection/components/BasicInformation.tsx
src/modules/inspection/components/InpectionDoc.tsx
src/modules/inspection/components/Report.tsx
src/modules/inspection/components/inspectionFormTags.tsx
src/modules/inspection/views/inspection/InspectionCreate.tsx

union documentos

---

src/modules/asegurabilidad/components/PolizaViewForm.tsx
src/modules/notificacions/components/Detail_notification.tsx
src/modules/notificacions/views/DropdownNotification.tsx
src/modules/notificacions/views/ListNotification.tsx

corrección notificaciones

---

src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/disposition/components/Precontractual/FormLider.tsx
src/modules/disposition/components/Precontractual/FormUser.tsx
src/modules/disposition/components/Precontractual/Lease/GeneralFormLease.tsx
src/modules/disposition/components/Precontractual/Lease/LeaseDoc.tsx
src/modules/disposition/components/Precontractual/Lease/LeasePdf.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoDoc.tsx
src/modules/users/components/DataformRole.tsx
src/modules/users/components/Dataformuser.tsx
src/modules/users/components/FormUserprueba.tsx
src/modules/users/redux/actions.ts
src/modules/users/redux/service/roles.ts
src/modules/users/redux/service/user.ts
src/modules/users/views/CreateUser.tsx
src/modules/users/views/EditUser.tsx
src/modules/users/views/UserList.tsx
src/modules/users/views/roles/ListRoles.tsx
src/utils/ui/months.tsx

cambios usuarios y roles

---

src/modules/acquisitions/components/en_des_globe/TablaGlobe.tsx
src/modules/acquisitions/components/en_des_globe/TableAreas.tsx
src/modules/notificacions/components/Detail_notification.tsx
src/modules/users/components/AssignRolePermitsView.tsx
src/modules/users/components/DataformRole.tsx
src/modules/users/components/Dataformuser.tsx
src/modules/users/components/FormUserprueba.tsx
src/modules/users/components/UserViewForm.tsx
src/modules/users/redux/service/user.ts
src/modules/users/views/DetailUser.tsx
src/modules/users/views/EditUser.tsx
src/utils/interfaces/users.ts

cambios formularios de usuarios y roles

cambios formularios de usuarios y roles

---

src/modules/users/redux/service/user.ts

corrección bug creación usuario

corrección bug creación usuario

---

src/config/store.ts
src/modules/acquisitions/components/RealEstateForm/DataRealEstateForm.tsx
src/modules/acquisitions/components/RealEstateForm/RealEstateViewForm.tsx
src/modules/acquisitions/components/RealEstateForm/index.tsx
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/disposition/components/Precontractual/FormLider.tsx
src/modules/disposition/components/Precontractual/FormRiskAnalysis.tsx
src/modules/disposition/components/Precontractual/FormUser.tsx
src/modules/disposition/components/Precontractual/Lease/Detail_Lease.tsx
src/modules/disposition/components/Precontractual/Lease/FormPrecontractualLease.tsx
src/modules/disposition/components/Precontractual/Lease/GeneralFormLease.tsx
src/modules/disposition/components/Precontractual/Lease/LeaseDoc.tsx
src/modules/disposition/components/Precontractual/Lease/LeasePdf.tsx
src/modules/disposition/components/Precontractual/PublicUse/GeneralFormPublicUse.tsx
src/modules/disposition/components/Precontractual/PublicUse/PubilcUsePdf.tsx
src/modules/disposition/components/Precontractual/ViewPerson.tsx
src/modules/disposition/components/Precontractual/ViewRiskAnalysis.tsx
src/modules/disposition/components/Precontractual/comodato/GeneralFormComodato.tsx
src/modules/disposition/redux/actions.ts
src/modules/disposition/redux/reducer.ts
src/modules/disposition/redux/service/precontracts.ts
src/modules/disposition/views/Pre-contractual/CreatePrecontractual.tsx
src/modules/disposition/views/Pre-contractual/DetailPrecontractual.tsx
src/modules/general_list/components/DependencyForm.tsx

Bugfix: correcion bug detalle bien inmueble

Bugfix: correcion bug detalle bien inmueble

---

src/modules/Inventory_record/components/TableDivideAreas.tsx
src/modules/Inventory_record/routes.ts
src/modules/Inventory_record/views/InventoryRecordEdit.tsx
src/modules/acquisitions/components/RealEstateForm/DataRealEstateForm.tsx
src/modules/acquisitions/components/RealEstateForm/RealEstateViewForm.tsx
src/modules/acquisitions/components/RealEstateForm/index.tsx
src/modules/acquisitions/components/RealEstateList.tsx
src/modules/acquisitions/views/RealEstate/CreateRealEstate.tsx
src/modules/disposition/components/Detail_disposition.tsx
src/modules/disposition/components/FormDisposition.tsx
src/modules/disposition/components/Precontractual/Lease/LeasePdf.tsx
src/modules/disposition/components/Precontractual/comodato/BeneficiaryForm.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoDoc.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoPdf.tsx
src/modules/disposition/components/Precontractual/comodato/Detail_comodato.tsx
src/modules/disposition/components/Precontractual/comodato/GeneralFormComodato.tsx
src/modules/disposition/components/TableDisposition.tsx
src/modules/disposition/redux/service/precontracts.ts
src/modules/disposition/views/DetailDisposition.tsx
src/modules/disposition/views/Pre-contractual/DetailPrecontractual.tsx
src/modules/notificacions/redux/service.ts
src/utils/components/template/sider.tsx

Bugfix: administracion de inventario

Bugfix: administracion de inventario

---

src/modules/acquisitions/components/RealEstateForm/index.tsx
src/modules/acquisitions/components/en_des_globe/TablaGlobe.tsx
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/disposition/components/Detail_disposition.tsx
src/modules/disposition/components/DispositionFormTags.tsx
src/modules/disposition/components/FormTypeDisposition.tsx
src/modules/disposition/components/Precontractual/FormLider.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoDoc.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoPdf.tsx
src/modules/disposition/components/Precontractual/comodato/Detail_comodato.tsx
src/modules/disposition/components/Precontractual/comodato/FormPrecontractualComodato.tsx
src/modules/disposition/components/Precontractual/comodato/GeneralFormComodato.tsx
src/modules/disposition/redux/actions.ts
src/modules/disposition/redux/service/index.ts
src/modules/disposition/redux/service/precontracts.ts
src/modules/disposition/routes.ts
src/modules/disposition/views/Pre-contractual/CreatePrecontractual.tsx
src/modules/disposition/views/Pre-contractual/DetailPrecontractual.tsx

Bugfix: correcion englobe y desenglobe

Bugfix: correcion englobe y desenglobe

---

src/modules/acquisitions/components/en_des_globe/TableAreas.tsx

bugfix: coreccion englobe

---

src/modules/users/components/FormUserprueba.tsx
src/modules/users/components/GerenalForm.tsx
src/utils/components/template/sider.tsx

[remover expedienté electronico]

remover expediente electronico

---

src/modules/disposition/components/Precontractual/Lease/FormPrecontractualLease.tsx
src/modules/disposition/components/Precontractual/Lease/GeneralFormLease.tsx
src/modules/disposition/components/Precontractual/Lease/LeaseDoc.tsx
src/modules/disposition/components/Precontractual/comodato/ComodatoDoc.tsx
src/modules/disposition/redux/service/precontracts.ts
src/utils/components/template/sider.tsx

fix: coreccion modulo gestion documental

fix: coreccion modulo gestion documental

---

src/modules/acquisitions/views/RealEstate/CreateRealEstate.tsx
src/modules/acquisitions/views/RealEstate/EditRealEstate.tsx
src/modules/disposition/views/Contracts/CreateContract.tsx
src/modules/inspection/components/inspectionFormTags.tsx
src/modules/notificacions/redux/service.ts

fix: notificaciones

---

src/config/store.ts
src/modules/acquisitions/redux/actions/realEstates.ts
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/acquisitions/views/RealEstate/CreateRealEstate.tsx
src/modules/asegurabilidad/components/PolizaForm.tsx
src/modules/asegurabilidad/views/Policies/EditPolicy.tsx
src/modules/disposition/components/Precontractual/FormLider.tsx
src/modules/disposition/components/Precontractual/FormUser.tsx
src/modules/disposition/components/Precontractual/Lease/FormPrecontractualLease.tsx
src/modules/disposition/components/Precontractual/Lease/GeneralFormLease.tsx
src/modules/disposition/components/Precontractual/Lease/LeaseDoc.tsx
src/modules/document_management/components/CollapseElectronicFiel.tsx
src/modules/document_management/components/ElectronicFielList.tsx
src/modules/document_management/redux/actions.ts
src/modules/document_management/redux/reducer.ts
src/modules/document_management/redux/service.ts
src/modules/document_management/redux/types.ts
src/modules/document_management/views/Electronic_file.tsx
src/modules/users/views/UserList.tsx
src/modules/users/views/Users.tsx
src/utils/components/template/sider.tsx
src/utils/ui/PersonaM/index.tsx

[Bugfix: coreccion poliza y expediente electronico]

Bugfix: coreccion poliza y expediente electronico

---

src/modules/disposition/components/Contractual/GeneralDataContract.tsx
src/modules/disposition/components/Contractual/Lease/LeaseDocContract.tsx
src/modules/disposition/components/Contractual/comodatoContract/ComodatoDocContract.tsx
src/modules/disposition/redux/actions.ts
src/modules/disposition/redux/service/contracts.ts
src/modules/disposition/views/Contracts/CreateContract.tsx
src/modules/disposition/views/EditDisposition.tsx
src/modules/document_management/components/CollapseElectronicFiel.tsx
src/modules/document_management/components/ModalElectronicFiel.tsx
src/modules/document_management/views/Electronic_file.tsx

[Feature: expediente electronico]

Feature: expediente electronico

---

src/modules/Inventory_record/components/TableDivideAreas.tsx
src/modules/acquisitions/components/ProjectForm.tsx
src/modules/acquisitions/components/RealEstateForm/AcquisitionForm.tsx
src/modules/acquisitions/components/RealEstateForm/DataRealEstateForm.tsx
src/modules/acquisitions/components/RealEstateList.tsx
src/modules/acquisitions/redux/services/realEstates.ts
src/modules/acquisitions/views/Projects/index.tsx
src/modules/asegurabilidad/components/InsuranceBrokerForm.tsx
src/modules/asegurabilidad/components/InsuranceCompanyForm.tsx
src/modules/disposition/components/Precontractual/comodato/FormPrecontractualComodato.tsx
src/modules/users/components/Dataformuser.tsx
src/modules/users/components/FormUserprueba.tsx
src/modules/users/components/GerenalForm.tsx
src/modules/users/redux/actions.ts
src/modules/users/redux/service/user.ts
src/modules/users/views/UserList.tsx
src/utils/components/Location/index.tsx
src/utils/ui/PersonaM/index.tsx

fix: correcciones generales

---

src/modules/Inventory_record/views/InventoryRecordList.tsx
src/modules/acquisitions/components/RealEstateForm/index.tsx
src/modules/acquisitions/components/RealEstateList.tsx
src/modules/asegurabilidad/redux/service/policy.ts
src/modules/disposition/components/Precontractual/FormRiskAnalysis.tsx
src/modules/disposition/components/Precontractual/PublicUse/FormPrecontractualPublicUse.tsx
src/modules/disposition/components/Precontractual/PublicUse/GeneralFormPublicUse.tsx
src/modules/disposition/components/Precontractual/comodato/BeneficiaryForm.tsx
src/modules/disposition/components/Precontractual/comodato/FormPrecontractualComodato.tsx
src/modules/inspection/components/BasicInformation.tsx
src/modules/inspection/components/CreateInspectionPhysical.tsx
src/modules/inspection/components/InspectionPhysicalForm.tsx
src/modules/inspection/components/OccupationForm.tsx
src/modules/inspection/components/Report.tsx
src/modules/inspection/components/inspectionFormTags.tsx
src/modules/inspection/custom_types.ts
src/utils/ui/PersonaM/index.tsx

BugFix: contratos proyectos

---

src/modules/disposition/components/Precontractual/FormUser.tsx
src/modules/disposition/components/Precontractual/PublicUse/GeneralFormPublicUse.tsx
src/utils/ui/importer.tsx

Bugfix: descargar documento cargue masivo

Bugfix: descargar documento cargue masivo
